/* ida_solver.c - optimal 2x2x2 solver using IDA* instead of a full BFS table.
 *
 * Same model, input and output as the repository's solver.c:
 *     ./ida_solver 21345671111111      ->  an optimal move sequence
 * The difference: solver.c builds a 3,674,160-entry table (17.5 MiB peak)
 * on every run; this program searches with two admissible pattern databases
 * from tables.h (about 112 KB, generated by gen_tables.c) and allocates
 * nothing at run time.
 *
 * One source, two builds:
 *   host:   cc -O2 -std=c99 ida_solver.c -o ida_solver
 *   RV32I:  riscv-none-elf-gcc -O2 -march=rv32i -mabi=ilp32 -ffreestanding \
 *               -nostdlib -fno-builtin -DTARGET -DSTATE=21345671111111 \
 *               -T ref.ld ida_solver.c -o ida_solver.elf
 * The TARGET build reads INPUT at compile time, prints through Ripes ecalls
 * and exits with the solution length (0..11), 254 if the self-check fails,
 * or 255 for invalid input.
 *
 * Search state, all stored as byte offsets so no lookup scales an index:
 *   p4 = 4 * permutation rank      offset into a PT row (32-bit entries)
 *   o2 = 2 * orientation rank      offset into an OT row (16-bit entries)
 *   x  = 8*pos(cubie 3)+pos(cubie 6)   offset into an XT row
 * PT entries are (p' << 6) | dP[p']: one load gives the next state and the
 * permutation heuristic. DX[(o2 << 5) | x] is the exact distance of the
 * (orientation, two-cubie position) abstraction. h = max(dP, DX) is
 * admissible, so IDA* returns a shortest solution.
 */
#include <stdint.h>
#include "tables.h"

#define MAXD 12 /* diameter is 11; one spare frame for the solved child */

/* ------------------------------------------------------------------ lookups */
static inline uint32_t pt(uint32_t f, uint32_t p4)
{
    return *(const uint32_t *) ((const uint8_t *) PT[f] + p4);
}
static inline uint32_t ot(uint32_t f, uint32_t o2)
{
    return *(const uint16_t *) ((const uint8_t *) OT[f] + o2);
}

/* -------------------------------------------------------------------- input */
/* 14 digits: positions 1..7 hold cubies '1'..'7' (each once), then seven
 * twists '1'..'3' whose internal values (digit - 1) sum to 0 mod 3. */
static int parse_state(const char *in, uint8_t *p, uint8_t *o)
{
    uint32_t seen = 0, sum = 0;
    for (int i = 0; i < 7; i++) {
        uint32_t d = (uint32_t) (uint8_t) in[i] - '1';
        if (d > 6 || (seen >> d & 1)) return 0;
        seen |= 1u << d;
        p[i] = (uint8_t) d;
    }
    for (int i = 0; i < 7; i++) {
        uint32_t d = (uint32_t) (uint8_t) in[7 + i] - '1';
        if (d > 2) return 0;
        o[i] = (uint8_t) d;
        sum += d;
    }
    /* sum <= 14, reduced mod 3 without a divide */
    if (sum >= 6) sum -= 6;
    if (sum >= 6) sum -= 6;
    if (sum >= 3) sum -= 3;
    return in[14] == 0 && sum == 0;
}

/* Search coordinates of a parsed state; every multiply is a shift-add. */
static void coords(const uint8_t *p, const uint8_t *o, uint32_t *p4,
                   uint32_t *o2, uint32_t *x)
{
    uint32_t c[7], q = 0, pa = 0, pb = 0;
    for (int i = 0; i < 7; i++) {
        uint32_t n = 0;
        for (int j = i + 1; j < 7; j++) n += p[j] < p[i];
        c[i] = n;
        if (p[i] == 3) pa = (uint32_t) i;
        if (p[i] == 6) pb = (uint32_t) i;
    }
    /* Lehmer rank by Horner's rule: r = r * (7 - i) + c[i] */
    uint32_t r = c[0];
    r = (r << 2) + (r << 1) + c[1]; /* x6 */
    r = (r << 2) + r + c[2];        /* x5 */
    r = (r << 2) + c[3];            /* x4 */
    r = (r << 1) + r + c[4];        /* x3 */
    r = (r << 1) + c[5];            /* x2; c[6] is always 0 */
    for (int i = 0; i < 6; i++) q = (q << 1) + q + o[i]; /* base 3 */
    *p4 = r << 2;
    *o2 = q << 1;
    *x = pa << 3 | pb;
}

/* --------------------------------------------------------------------- IDA* */
typedef struct {
    uint32_t p4, o2, x; /* node at this depth */
    uint32_t last;      /* face of the move into this node, 3 = none */
    uint32_t face;      /* face being expanded */
    uint32_t turn;      /* quarter turns applied so far on that face */
} frame_t;

/* Writes moves (3 * face + turns - 1) to path; returns the length, or -1
 * if no solution of length <= 11 exists (impossible for a valid state). */
static int ida(uint32_t p4, uint32_t o2, uint32_t x, uint8_t *path)
{
    frame_t st[MAXD + 1];
    /* R^4 is the identity, so the 4th R lookup returns to p and its entry
     * carries dP[p]: the root heuristic needs no separate table. */
    uint32_t w = pt(0, p4);
    w = pt(0, w >> 4);
    w = pt(0, w >> 4);
    w = pt(0, w >> 4);
    uint32_t h1 = w & 15, h2 = DX[o2 << 5 | x];
    uint32_t bound = h1 > h2 ? h1 : h2;
    if (bound == 0) return 0; /* already solved */

    for (;; bound++) {
        if (bound > 11) return -1;
        frame_t *fp = st;
        fp->p4 = p4, fp->o2 = o2, fp->x = x, fp->last = 3;
        uint32_t rem = bound - 1; /* largest h a child may have */
    enter:
        fp->face = fp->last == 0 ? 1 : 0; /* never turn the same face twice */
    face:
        {
            uint32_t f = fp->face, t;
            uint32_t a = fp->p4, b = fp->o2, c = fp->x;
            /* children of face f are 1, 2, 3 successive quarter turns */
            for (t = 1; t <= 3; t++) {
                uint32_t e = pt(f, a);
                a = e >> 4;
                b = ot(f, b);
                c = XT[f][c];
                /* g + 1 + h <= bound  <=>  h1 <= rem && h2 <= rem */
                if ((e & 15) > rem) continue;
                uint32_t g = DX[b << 5 | c];
                if (g > rem) continue;
                fp->turn = t;
                if (((e & 15) | g) == 0) { /* h = 0 only at solved */
                    /* IDA* reaches the goal only at depth == bound, so
                     * rem is 0 here. Using bound avoids fp - st, a divide
                     * by sizeof(frame_t) = 24 that GCC turns into
                     * __mulsi3 on RV32I. */
                    if (rem != 0) return -1;
                    int n = (int) bound;
                    for (int i = 0; i < n; i++)
                        path[i] = (uint8_t) (st[i].face * 3 + st[i].turn - 1);
                    return n;
                }
                fp[1].p4 = a, fp[1].o2 = b, fp[1].x = c, fp[1].last = f;
                fp++;
                rem--;
                goto enter;
            resume: /* back from a child: continue with the next turn */
                f = fp->face;
                t = fp->turn;
                a = fp[1].p4, b = fp[1].o2, c = fp[1].x;
            }
        }
        do fp->face++; /* next face, skipping the one just turned */
        while (fp->face == fp->last);
        if (fp->face < 3) goto face;
        if (fp == st) continue; /* bound exhausted: raise it */
        fp--;
        rem++;
        goto resume;
    }
}

/* -------------------------------------------- independent self-check (T5) */
/* Replays the path with the repository's source/twist rule, which shares
 * nothing with the search tables, and confirms the cube ends solved. */
static const uint8_t SRC[3][7] = {
    {1, 4, 2, 0, 3, 5, 6}, {0, 1, 2, 4, 5, 6, 3}, {0, 2, 5, 3, 1, 4, 6}};
static const uint8_t TW[3][7] = {
    {1, 2, 0, 2, 1, 0, 0}, {0, 0, 0, 1, 2, 1, 2}, {0, 0, 0, 0, 0, 0, 0}};

static void quarter(uint8_t *p, uint8_t *o, uint32_t f)
{
    uint8_t np[7], no[7];
    for (int i = 0; i < 7; i++) {
        uint32_t s = SRC[f][i], v = o[s] + TW[f][i];
        np[i] = p[s];
        no[i] = (uint8_t) (v >= 3 ? v - 3 : v); /* v <= 4: one subtract */
    }
    for (int i = 0; i < 7; i++) p[i] = np[i], o[i] = no[i];
}

static int verify_path(uint8_t *p, uint8_t *o, const uint8_t *path, int n)
{
    for (int i = 0; i < n; i++) {
        uint32_t m = path[i], f = 0;
        if (m >= 9) return 0;
        while (m >= 3) m -= 3, f++;
        for (uint32_t t = 0; t <= m; t++) quarter(p, o, f);
    }
    for (int i = 0; i < 7; i++)
        if (p[i] != i || o[i]) return 0;
    return 1;
}

static const char NAMES[9][3] = {"R",  "R2", "R'", "B", "B2",
                                 "B'", "D",  "D2", "D'"};

/* ------------------------------------------------------------- host build */
#ifndef TARGET
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv)
{
    uint8_t p[7], o[7], q[7], r[7], path[16];
    uint32_t p4, o2, x;
    if (argc != 2 || !parse_state(argv[1], p, o)) {
        fprintf(stderr, "usage: %s PPPPPPPOOOOOOO\n",
                argc > 0 && argv[0] ? argv[0] : "ida_solver");
        return 2;
    }
    coords(p, o, &p4, &o2, &x);
    int n = ida(p4, o2, x, path);
    memcpy(q, p, 7);
    memcpy(r, o, 7);
    if (n < 0 || !verify_path(q, r, path, n)) {
        fputs("internal error: no verified solution\n", stderr);
        return 1;
    }
    for (int i = 0; i < n; i++) printf("%s%s", i ? " " : "", NAMES[path[i]]);
    putchar('\n');
    return fflush(stdout) != 0 || ferror(stdout);
}

/* ---------------------------------------------- RV32I build for Ripes ELF */
#else
/* -DSTATE=21345671111111 (no quotes needed, easy from cmd/PowerShell)
 * or -DINPUT='"21345671111111"'; default is the reporting vector. */
#define STR2(s) #s
#define STR(s) STR2(s)
#ifndef INPUT
#ifdef STATE
#define INPUT STR(STATE)
#else
#define INPUT "21345671111111"
#endif
#endif
static const char input[] = INPUT;

static void ecall2(uint32_t a0, uint32_t a7)
{
    register uint32_t r0 __asm__("a0") = a0, r7 __asm__("a7") = a7;
    __asm__ volatile("ecall" : "+r"(r0) : "r"(r7) : "memory");
}
static void print(const char *s) { ecall2((uint32_t) (uintptr_t) s, 4); }
static void __attribute__((noreturn)) exit_with(uint32_t code)
{
    ecall2(code, 93);
    for (;;) {}
}

void __attribute__((section(".text._start"), noreturn)) _start(void)
{
    uint8_t p[7], o[7], q[7], r[7], path[16];
    uint32_t p4, o2, x;
    if (!parse_state(input, p, o)) exit_with(255);
    coords(p, o, &p4, &o2, &x);
    int n = ida(p4, o2, x, path);
    for (int i = 0; i < 7; i++) q[i] = p[i], r[i] = o[i];
    if (n < 0 || !verify_path(q, r, path, n)) exit_with(254);
    for (int i = 0; i < n; i++) {
        if (i) print(" ");
        print(NAMES[path[i]]);
    }
    print("\n");
    exit_with((uint32_t) n);
}
#endif